int = input('Enter any number: ')
float = input("Enter any float number: ")
print(int + float)
print(int - float)
print(float - int)
print(int * float)
print(int / float)
print(int // float)
print(int % float)
print(int ** float)